import type { Exercise } from './types';

/**
 * Sample exercises for development and initial database population.
 * Covers different body areas, intensities, progression levels, and pathways.
 */
export const SEED_EXERCISES: Partial<Exercise>[] = [
  {
    name: 'Gentle Neck Stretch',
    description:
      'A slow, controlled neck stretch targeting the upper trapezius and levator scapulae. Tilt your head to each side, hold for 20 seconds, and repeat.',
    video_url: 'https://player.vimeo.com/video/placeholder-001',
    duration_minutes: 5,
    intensity: 'low',
    progression_level: 'beginner',
    is_active: true,
    tags: {
      body_area: ['neck'],
      pain_relief: true,
      stress_reduction: false,
      sleep_optimization: false,
      digestion: false,
      mindset: false,
      mobility: true,
      contraindications: ['acute cervical disc herniation'],
    },
    pathway_ids: ['neck-pain-relief'],
  },
  {
    name: 'Cat-Cow Spinal Flow',
    description:
      'Alternate between arching and rounding the spine on all fours. This classic movement improves spinal mobility and relieves back tension.',
    video_url: 'https://player.vimeo.com/video/placeholder-002',
    duration_minutes: 8,
    intensity: 'low',
    progression_level: 'beginner',
    is_active: true,
    tags: {
      body_area: ['back'],
      pain_relief: true,
      stress_reduction: true,
      sleep_optimization: false,
      digestion: false,
      mindset: false,
      mobility: true,
      contraindications: ['severe spinal stenosis'],
    },
    pathway_ids: ['back-pain-relief', 'mobility-restoration'],
  },
  {
    name: 'Diaphragmatic Breathing',
    description:
      'Lie on your back with knees bent and practice deep belly breathing. Inhale for 4 counts, hold for 4, exhale for 6. Calms the nervous system.',
    video_url: 'https://player.vimeo.com/video/placeholder-003',
    duration_minutes: 10,
    intensity: 'low',
    progression_level: 'beginner',
    is_active: true,
    tags: {
      body_area: ['full_body'],
      pain_relief: false,
      stress_reduction: true,
      sleep_optimization: true,
      digestion: true,
      mindset: true,
      mobility: false,
      contraindications: [],
    },
    pathway_ids: ['stress-reduction', 'sleep-improvement'],
  },
  {
    name: 'Shoulder CARs',
    description:
      'Controlled Articular Rotations for the shoulder joint. Slowly trace the largest pain-free circle with your arm to maintain joint health.',
    video_url: 'https://player.vimeo.com/video/placeholder-004',
    duration_minutes: 6,
    intensity: 'medium',
    progression_level: 'intermediate',
    is_active: true,
    tags: {
      body_area: ['shoulder'],
      pain_relief: true,
      stress_reduction: false,
      sleep_optimization: false,
      digestion: false,
      mindset: false,
      mobility: true,
      contraindications: ['shoulder dislocation', 'rotator cuff tear'],
    },
    pathway_ids: ['mobility-restoration'],
  },
  {
    name: 'Hip Flexor Release',
    description:
      'A half-kneeling hip flexor stretch combined with gentle pelvic tilts. Targets the iliopsoas to relieve tightness from prolonged sitting.',
    video_url: 'https://player.vimeo.com/video/placeholder-005',
    duration_minutes: 7,
    intensity: 'medium',
    progression_level: 'beginner',
    is_active: true,
    tags: {
      body_area: ['hip', 'back'],
      pain_relief: true,
      stress_reduction: false,
      sleep_optimization: false,
      digestion: false,
      mindset: false,
      mobility: true,
      contraindications: ['hip replacement within 6 weeks'],
    },
    pathway_ids: ['back-pain-relief', 'mobility-restoration'],
  },
  {
    name: 'Progressive Muscle Relaxation',
    description:
      'Systematically tense and release each muscle group from toes to head. Promotes full-body relaxation and improved sleep onset.',
    video_url: 'https://player.vimeo.com/video/placeholder-006',
    duration_minutes: 15,
    intensity: 'low',
    progression_level: 'beginner',
    is_active: true,
    tags: {
      body_area: ['full_body'],
      pain_relief: false,
      stress_reduction: true,
      sleep_optimization: true,
      digestion: false,
      mindset: true,
      mobility: false,
      contraindications: [],
    },
    pathway_ids: ['stress-reduction', 'sleep-improvement', 'general-wellness'],
  },
  {
    name: 'Knee Stability Circuit',
    description:
      'A circuit of mini-band walks, single-leg balances, and terminal knee extensions to build stability around the knee joint.',
    video_url: 'https://player.vimeo.com/video/placeholder-007',
    duration_minutes: 12,
    intensity: 'medium',
    progression_level: 'intermediate',
    is_active: true,
    tags: {
      body_area: ['knee'],
      pain_relief: true,
      stress_reduction: false,
      sleep_optimization: false,
      digestion: false,
      mindset: false,
      mobility: true,
      contraindications: ['acute ACL injury', 'post-surgical knee within 8 weeks'],
    },
    pathway_ids: ['mobility-restoration'],
  },
  {
    name: 'Full Body Morning Flow',
    description:
      'A dynamic full-body warm-up combining sun salutations, gentle twists, and hip openers. Ideal for starting the day with energy and focus.',
    video_url: 'https://player.vimeo.com/video/placeholder-008',
    duration_minutes: 20,
    intensity: 'medium',
    progression_level: 'intermediate',
    is_active: true,
    tags: {
      body_area: ['full_body'],
      pain_relief: false,
      stress_reduction: true,
      sleep_optimization: false,
      digestion: true,
      mindset: true,
      mobility: true,
      contraindications: [],
    },
    pathway_ids: ['general-wellness', 'mobility-restoration'],
  },
  {
    name: 'Advanced Spinal Mobility',
    description:
      'A challenging sequence of segmental spinal rotations, Jefferson curls, and thoracic extensions for those with a solid movement foundation.',
    video_url: 'https://player.vimeo.com/video/placeholder-009',
    duration_minutes: 15,
    intensity: 'high',
    progression_level: 'advanced',
    is_active: true,
    tags: {
      body_area: ['back', 'neck'],
      pain_relief: false,
      stress_reduction: false,
      sleep_optimization: false,
      digestion: false,
      mindset: false,
      mobility: true,
      contraindications: ['disc herniation', 'osteoporosis', 'acute back pain'],
    },
    pathway_ids: ['mobility-restoration', 'back-pain-relief'],
  },
  {
    name: 'Evening Wind-Down Routine',
    description:
      'A calming sequence of gentle stretches, guided breathing, and body-scan meditation designed to prepare the body and mind for restful sleep.',
    video_url: 'https://player.vimeo.com/video/placeholder-010',
    duration_minutes: 12,
    intensity: 'low',
    progression_level: 'beginner',
    is_active: true,
    tags: {
      body_area: ['full_body'],
      pain_relief: false,
      stress_reduction: true,
      sleep_optimization: true,
      digestion: false,
      mindset: true,
      mobility: false,
      contraindications: [],
    },
    pathway_ids: ['sleep-improvement', 'stress-reduction', 'general-wellness'],
  },
];
